package com.company.logicdelete.analyzer;

import com.company.logicdelete.common.*;import picocli.CommandLine;import java.nio.file.*;import java.util.*;import java.util.concurrent.Callable;

@CommandLine.Command(name="logic-delete-analyzer",mixinStandardHelpOptions=true,subcommands={Main.Scan.class,Main.Coverage.class})
public class Main implements Runnable {public static void main(String[]args){List<String>a=new ArrayList<>(Arrays.asList(args));if(a.isEmpty()||a.get(0).startsWith("--"))a.add(0,"scan");System.exit(new CommandLine(new Main()).execute(a.toArray(new String[0])));}public void run(){new CommandLine(this).usage(System.out);}
 @CommandLine.Command(name="scan",description="Scan MyBatis openGauss mapper XML files") static class Scan implements Callable<Integer>{@CommandLine.Option(names="--project",required=true)Path project;@CommandLine.Option(names="--config",required=true)Path config;@CommandLine.Option(names="--output",required=true)Path output;@CommandLine.Option(names="--xml-mode",defaultValue="compatible")String xmlMode;
 public Integer call()throws Exception{LogicDeleteConfig c=ConfigLoader.load(config);List<Path>files=new MapperScanner().scan(project,c.getScan());MapperParser parser=new MapperParser();List<AnalysisModels.Statement> statements=new ArrayList<>();Map<String,AnalysisModels.Fragment> fragments=new HashMap<>();for(Path p:files){MapperParser.Parsed x=parser.parse(p,"safe".equalsIgnoreCase(xmlMode));statements.addAll(x.statements);for(AnalysisModels.Fragment f:x.fragments)fragments.put(f.fullId(),f);}for(AnalysisModels.Statement s:statements)expand(s,fragments,0,new HashSet<String>());List<AnalysisModels.Result>results=new ArrayList<>();SqlAnalyzer analyzer=new SqlAnalyzer();for(AnalysisModels.Statement s:statements)results.add(analyzer.analyze(s,c));new ReportWriter().write(output,results);System.out.println("Scanned "+files.size()+" mapper files and "+statements.size()+" statements. Report: "+output.toAbsolutePath());return 0;}
 private void expand(AnalysisModels.Statement s,Map<String,AnalysisModels.Fragment>fs,int depth,Set<String>stack){java.util.regex.Matcher m=java.util.regex.Pattern.compile("__INCLUDE__(.*?)__").matcher(s.sql);StringBuffer b=new StringBuffer();while(m.find()){String ref=m.group(1);if(ref.contains("${")){s.dynamicInclude=true;m.appendReplacement(b,"");continue;}String full=ref.contains(".")?ref:s.namespace+"."+ref;AnalysisModels.Fragment f=fs.get(full);if(f==null){s.includeSuccess=false;s.expansionRisks.add("INCLUDE_NOT_FOUND");m.appendReplacement(b,"");}else if(depth>=10||!stack.add(full)){s.includeSuccess=false;s.expansionRisks.add("INCLUDE_RECURSION_LIMIT");m.appendReplacement(b,"");}else{AnalysisModels.Statement nested=new AnalysisModels.Statement();nested.namespace=f.namespace;nested.sql=MapperParser.nodeText(f.element);expand(nested,fs,depth+1,stack);stack.remove(full);s.expansionRisks.addAll(nested.expansionRisks);m.appendReplacement(b,java.util.regex.Matcher.quoteReplacement(nested.sql));}}m.appendTail(b);s.sql=b.toString();}}
 @CommandLine.Command(name="coverage",description="Compare affected and runtime SQL IDs")static class Coverage implements Callable<Integer>{@CommandLine.Option(names="--affected",required=true)Path affected;@CommandLine.Option(names="--runtime-log",required=true)Path runtime;@CommandLine.Option(names="--static-detail")Path detail;@CommandLine.Option(names="--output",required=true)Path output;public Integer call()throws Exception{new CoverageAnalyzer().run(affected,runtime,output);System.out.println("Coverage report: "+output.toAbsolutePath());return 0;}}
}
