package com.company.logicdelete.analyzer;

import org.w3c.dom.*;import org.xml.sax.InputSource;import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;import javax.xml.parsers.*;

final class MapperParser {
    static final class Parsed {final List<AnalysisModels.Statement> statements=new ArrayList<>();final List<AnalysisModels.Fragment> fragments=new ArrayList<>();}
    Parsed parse(Path path, boolean safe) throws Exception {DocumentBuilderFactory f=DocumentBuilderFactory.newInstance();f.setFeature("http://xml.org/sax/features/external-general-entities",false);f.setFeature("http://xml.org/sax/features/external-parameter-entities",false);f.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd",false);if(safe)f.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);f.setXIncludeAware(false);f.setExpandEntityReferences(false);DocumentBuilder b=f.newDocumentBuilder();b.setEntityResolver((p,s)->new InputSource(new StringReader("")));Document d=b.parse(path.toFile());Element root=d.getDocumentElement();String ns=root.getAttribute("namespace");Parsed out=new Parsed();NodeList nodes=root.getChildNodes();for(int i=0;i<nodes.getLength();i++)if(nodes.item(i)instanceof Element){Element e=(Element)nodes.item(i);String tag=e.getTagName();if("sql".equals(tag)){AnalysisModels.Fragment x=new AnalysisModels.Fragment();x.namespace=ns;x.id=e.getAttribute("id");x.element=e;out.fragments.add(x);}else if(Arrays.asList("select","insert","update","delete").contains(tag)){AnalysisModels.Statement s=new AnalysisModels.Statement();s.file=path;s.namespace=ns;s.id=e.getAttribute("id");s.tag=tag;s.sql=nodeText(e);s.dynamic=hasDynamic(e);s.dynamicInclude=hasDynamicInclude(e);s.line=findLine(path,"id=\""+s.id+"\"");out.statements.add(s);}}return out;}
    static String nodeText(Node n){StringBuilder s=new StringBuilder();NodeList c=n.getChildNodes();for(int i=0;i<c.getLength();i++){Node x=c.item(i);if(x.getNodeType()==Node.TEXT_NODE||x.getNodeType()==Node.CDATA_SECTION_NODE)s.append(x.getNodeValue()).append(' ');else if(x instanceof Element){Element e=(Element)x;if("include".equals(e.getTagName()))s.append(" __INCLUDE__").append(e.getAttribute("refid")).append("__ ");else s.append(nodeText(e));}}return s.toString();}
    private static boolean hasDynamic(Element e){return e.getTextContent().contains("${")||hasTag(e,new HashSet<>(Arrays.asList("if","choose","when","otherwise","trim","where","set","foreach","bind")));}private static boolean hasTag(Node n,Set<String> tags){if(n instanceof Element&&tags.contains(((Element)n).getTagName()))return true;NodeList c=n.getChildNodes();for(int i=0;i<c.getLength();i++)if(hasTag(c.item(i),tags))return true;return false;}private static boolean hasDynamicInclude(Element e){NodeList x=e.getElementsByTagName("include");for(int i=0;i<x.getLength();i++)if(((Element)x.item(i)).getAttribute("refid").contains("${"))return true;return false;}
    private static int findLine(Path p,String needle){try{List<String> l=Files.readAllLines(p,StandardCharsets.UTF_8);for(int i=0;i<l.size();i++)if(l.get(i).contains(needle))return i+1;}catch(IOException ignored){}return 0;}
}
