package com.company.logicdelete.analyzer;

import com.fasterxml.jackson.databind.ObjectMapper;import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;

final class ReportWriter {
    void write(Path out,List<AnalysisModels.Result> results)throws IOException{Files.createDirectories(out);try(BufferedWriter d=Files.newBufferedWriter(out.resolve("logic-delete-detail.csv"),StandardCharsets.UTF_8);BufferedWriter risks=Files.newBufferedWriter(out.resolve("logic-delete-risk.csv"),StandardCharsets.UTF_8);BufferedWriter ids=Files.newBufferedWriter(out.resolve("affected-sql-ids.txt"),StandardCharsets.UTF_8)){d.write("fullSqlId,filePath,startLine,sqlCommandType,referencedTables,matchedControlledTables,containsDeleteFlag,physicalDelete,dynamicSql,riskLevel,riskCodes,evidenceSql\n");risks.write("fullSqlId,riskLevel,riskCode,message,filePath,startLine\n");for(AnalysisModels.Result r:results){d.write(csv(r.sqlId,r.file,String.valueOf(r.line),r.type,join(r.tables),join(r.controlled),String.valueOf(r.deleteFlag),String.valueOf(r.physicalDelete),String.valueOf(r.dynamic),r.level(),r.codes(),r.evidence)+"\n");if(!r.controlled.isEmpty())ids.write(r.sqlId+"\n");for(AnalysisModels.Risk x:r.risks)risks.write(csv(r.sqlId,x.level,x.code,x.message,r.file,String.valueOf(r.line))+"\n");}}
        writeSummary(out,results);new ObjectMapper().writerWithDefaultPrettyPrinter().writeValue(out.resolve("scan-result.json").toFile(),toJson(results));writeHtml(out.resolve("logic-delete-report.html"),results);}
    private void writeSummary(Path out,List<AnalysisModels.Result> rs)throws IOException{Map<String,int[]> m=new TreeMap<>();for(AnalysisModels.Result r:rs)for(String t:r.controlled){int[] a=m.computeIfAbsent(t,k->new int[5]);a[0]++;if("SELECT".equals(r.type))a[1]++;if("INSERT".equals(r.type))a[2]++;if("UPDATE".equals(r.type))a[3]++;if("DELETE".equals(r.type))a[4]++;}try(BufferedWriter w=Files.newBufferedWriter(out.resolve("logic-delete-summary.csv"),StandardCharsets.UTF_8)){w.write("table,referencedSqlCount,selectCount,insertCount,updateCount,deleteCount\n");for(Map.Entry<String,int[]>e:m.entrySet())w.write(csv(e.getKey(),String.valueOf(e.getValue()[0]),String.valueOf(e.getValue()[1]),String.valueOf(e.getValue()[2]),String.valueOf(e.getValue()[3]),String.valueOf(e.getValue()[4]))+"\n");}}
    private List<Map<String,Object>> toJson(List<AnalysisModels.Result> rs){List<Map<String,Object>> out=new ArrayList<>();for(AnalysisModels.Result r:rs){Map<String,Object>x=new LinkedHashMap<>();x.put("fullSqlId",r.sqlId);x.put("filePath",r.file);x.put("startLine",r.line);x.put("sqlCommandType",r.type);x.put("referencedTables",r.tables);x.put("matchedControlledTables",r.controlled);x.put("containsDeleteFlag",r.deleteFlag);x.put("physicalDelete",r.physicalDelete);x.put("riskLevel",r.level());x.put("riskCodes",r.codes());out.add(x);}return out;}
    private void writeHtml(Path p,List<AnalysisModels.Result>rs)throws IOException{StringBuilder b=new StringBuilder("<!doctype html><meta charset=utf-8><title>Logic delete report</title><style>body{font-family:sans-serif;margin:2rem}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccc;padding:.5rem;text-align:left}.HIGH{background:#ffd9d9}.MEDIUM{background:#fff2cc}</style><h1>Logic delete analysis</h1><table><tr><th>SQL ID</th><th>Type</th><th>Controlled tables</th><th>Risk</th><th>Codes</th></tr>");for(AnalysisModels.Result r:rs)b.append("<tr class='").append(r.level()).append("'><td>").append(esc(r.sqlId)).append("</td><td>").append(r.type).append("</td><td>").append(esc(join(r.controlled))).append("</td><td>").append(r.level()).append("</td><td>").append(esc(r.codes())).append("</td></tr>");b.append("</table>");Files.write(p,b.toString().getBytes(StandardCharsets.UTF_8));}
    static String csv(String...v){StringJoiner j=new StringJoiner(",");for(String x:v)j.add("\""+(x==null?"":x.replace("\"","\"\""))+"\"");return j.toString();}private static String join(Collection<String>x){return String.join("|",x);}private static String esc(String x){return x==null?"":x.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
}
