package com.company.logicdelete.analyzer;

import com.company.logicdelete.common.*;import java.time.LocalDate;import java.util.*;import java.util.regex.*;

final class SqlAnalyzer {
    private static final Pattern TABLE=Pattern.compile("(?i)\\b(?:from|join|update|delete\\s+from|insert\\s+into|merge\\s+into|using)\\s+((?:\"[^\"]+\"|[a-z_$][\\w$]*)(?:\\s*\\.\\s*(?:\"[^\"]+\"|[a-z_$][\\w$]*))?)");
    AnalysisModels.Result analyze(AnalysisModels.Statement s, LogicDeleteConfig config){AnalysisModels.Result r=new AnalysisModels.Result();r.sqlId=s.fullId();r.file=s.file.toString();r.line=s.line;r.evidence=s.sql.replaceAll("\\s+"," ").trim();r.dynamic=s.dynamic;String clean=SqlUtils.maskCommentsAndLiterals(s.sql);String norm=clean.toLowerCase();r.type=command(norm,s.tag);Matcher m=TABLE.matcher(clean);while(m.find()){String t=m.group(1).replaceAll("\\s","").replace("\"","").toLowerCase();if(!t.startsWith("${"))r.tables.add(t);}
        for(LogicDeleteConfig.ControlledTable t:config.getTables())for(String found:r.tables)if(found.equals(t.shortName())||found.equals(t.qualifiedName())||found.endsWith("."+t.shortName())){r.controlled.add(t.qualifiedName());if(field(norm,t.getDeleteField()))r.deleteFlag=true;}
        if(norm.matches("(?s).*(?:from|join|update|into)\\s+\\$\\{.*")){risk(r,"HIGH","DYNAMIC_TABLE_OR_COLUMN","Dynamic table or column cannot be resolved");}
        if(s.dynamicInclude)risk(r,"UNKNOWN","DYNAMIC_INCLUDE","Dynamic include cannot be expanded");for(String code:s.expansionRisks)risk(r,"UNKNOWN",code,"Include expansion was incomplete");
        if(!r.controlled.isEmpty()){r.physicalDelete="DELETE".equals(r.type);if(r.physicalDelete){LogicDeleteConfig.WhiteListItem w=whitelist(config,r.sqlId);if(w==null)risk(r,"HIGH","PHYSICAL_DELETE_ON_CONTROLLED_TABLE","Physical DELETE targets a controlled table");else if(w.getExpireDate()!=null&&w.getExpireDate().isBefore(LocalDate.now()))risk(r,"HIGH","PHYSICAL_DELETE_WHITELIST_EXPIRED","Physical-delete whitelist has expired");else risk(r,"LOW","PHYSICAL_DELETE_WHITELISTED","Physical DELETE is whitelisted");}else if("INSERT".equals(r.type)&&!r.deleteFlag)risk(r,norm.matches("(?s).*insert\\s+into\\s+[^ (]+\\s*\\(.*")?"MEDIUM":"UNKNOWN",norm.contains("(")?"INSERT_MISSING_DELETE_FLAG":"INSERT_WITHOUT_COLUMN_LIST","INSERT does not explicitly initialize delete flag");else if(!r.deleteFlag)risk(r,"UPDATE".equals(r.type)?"MEDIUM":"HIGH","UPDATE".equals(r.type)?"UPDATE_WITHOUT_DELETE_FLAG_CONDITION":"MISSING_DELETE_FLAG","Controlled table SQL does not contain delete flag");else risk(r,"INFO","HAS_DELETE_FLAG","SQL contains delete flag");if(r.controlled.size()>1&&r.deleteFlag)risk(r,"MEDIUM","MULTI_TABLE_DELETE_FLAG_NEED_REVIEW","Multiple controlled tables require alias-level review");}
        return r;}
    private static String command(String sql,String fallback){Matcher m=Pattern.compile("(?i)\\b(select|insert|update|delete|merge)\\b").matcher(sql);return m.find()?m.group(1).toUpperCase():fallback.toUpperCase();}private static boolean field(String s,String f){return f!=null&&Pattern.compile("(?i)(^|[^a-z0-9_])"+Pattern.quote(f)+"([^a-z0-9_]|$)").matcher(s).find();}private static void risk(AnalysisModels.Result r,String l,String c,String m){r.risks.add(new AnalysisModels.Risk(l,c,m));}private static LogicDeleteConfig.WhiteListItem whitelist(LogicDeleteConfig c,String id){if(c.getWhitelist()!=null&&c.getWhitelist().getPhysicalDelete()!=null)for(LogicDeleteConfig.WhiteListItem w:c.getWhitelist().getPhysicalDelete())if(id.equals(w.getSqlId()))return w;return null;}
}
